import { Database } from 'bun:sqlite'
import { latestMigrationVersion, runMigrations } from '../src/migrations'

// Regenerate only when deliberately moving the baseline forward.
const database = new Database(':memory:')
runMigrations(database, undefined, { useBaseline: false })
const quote = (name: string) => `"${name.replaceAll('"', '""')}"`
const shadowTables = new Set((database.query('PRAGMA table_list').all() as { name: string; type: string }[])
  .filter(table => table.type === 'shadow').map(table => table.name))
const schema = (database.query(`SELECT type,name,sql FROM sqlite_master
  WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%'
  ORDER BY CASE type WHEN 'table' THEN 0 WHEN 'index' THEN 1 ELSE 2 END,rowid`).all() as {
  type: string; name: string; sql: string
}[]).filter(entry => !shadowTables.has(entry.name))
const statements = schema.filter(entry => entry.type !== 'trigger').map(entry => `${entry.sql};`)
for (const table of schema.filter(entry => entry.type === 'table' && !entry.sql.startsWith('CREATE VIRTUAL TABLE'))) {
  const rows = database.query(`SELECT * FROM ${quote(table.name)}`).all() as Record<string, unknown>[]
  for (const row of rows) {
    const values = Object.entries(row).map(([column, value]) => {
      if (column === 'created_at') return 'CURRENT_TIMESTAMP'
      if (column === 'refreshed_at') return "strftime('%Y-%m-%dT%H:%M:%fZ','now')"
      if (value === null) return 'NULL'
      if (typeof value === 'number') return String(value)
      if (typeof value === 'string') return `'${value.replaceAll("'", "''")}'`
      throw new Error(`Unsupported baseline value in ${table.name}.${column}`)
    })
    statements.push(`INSERT INTO ${quote(table.name)}(${Object.keys(row).map(quote).join(',')}) VALUES(${values.join(',')});`)
  }
}
statements.push(...schema.filter(entry => entry.type === 'trigger').map(entry => `${entry.sql};`))
await Bun.write(new URL('../src/database-schema.ts', import.meta.url),
  `// Generated by bun scripts/rebase-database-schema.ts; do not edit by hand.\n`
  + `export const baselineVersion = ${latestMigrationVersion}\n`
  + `export const baselineSchema = [\n${statements.map(statement => `  ${JSON.stringify(statement)},`).join('\n')}\n].join('\\n')\n`)
database.close()
